### ISSUE TITLE
[Pomysł] Dodać path resolver/module resolution do konfiguracji aby ścieżki w projekcie były absolutne

### ISSUE THREAD

**Issue by adamklepacz** [typeofweb/polskifrontend#110]
## Czy Twój pomysł jest odpowiedzią na jakiś problem?

Korzystając z mozliwości extendowania configu w Next.js można dodać path resolver który znacznie poprawie czytelność ścieżek do modułów w projekcie.

## Opisz swoje rozwiązanie

Dodać aliasowanie ścieżek przy użyciu `tsconfig.json` jak w dokumentacji:
https://nextjs.org/docs/advanced-features/module-path-aliases

## Jakie są alternatywy?

Alternatywnie dodanie aliasowania ścieżek w `jsconfig.json` lub w `next.config.js` w celu extendowania configu webpacka.

## Dodatkowe informacje

…

**Comment by mmiszy** [comment]
Jaki problem to rozwiązuje?

**Comment by adamklepacz** [comment]
Problem czytelności importów 🙂 
Na przykład zmiana tego: 

```
import type { ArticlePageProps } from '../../pages/artykuly/[slug]';
import { detectContentGenre } from '../../utils/creator-utils';
import { formatDate } from '../../utils/date-utils';
import { addTrackingToLink } from '../../utils/link-utils';
import { Button } from '../Button/Button';
```

na to:

```
import type { ArticlePageProps } from 'pages/artykuly/[slug]';
import { detectContentGenre } from 'utils/creator-utils';
import { formatDate } from 'utils/date-utils';
import { addTrackingToLink } from 'utils/link-utils';
import { Button } from 'components/Button/Button';
```

**Comment by mmiszy** [comment]
https://nextjs.org/docs/advanced-features/module-path-aliases
