### ISSUE TITLE
[BUG] Błędny serwis (SPAM)

### ISSUE THREAD

**Issue by jcubic** [typeofweb/polskifrontend#148]
## Opis błędu

Ktoś zgłosił serwis highlab.pl który jest głównie o sprzęcie i aplikacjach, więc to taki spam nie mający nic wspólnego z Front-Endem.

## Jak powtórzyć problem

Przykład artykułu:

"Rozpoznawanie muzyki z Google – czy to możliwe?"

który jest o używaniu aplikacji od Google.

**Comment by mmiszy** [comment]
Usunięte. Strona się przebuduje przy najbliższej okazji.

Dzięki!
