### ISSUE TITLE
[BUG] Chyba przestał działać serwis

### ISSUE THREAD

**Issue by jcubic** [typeofweb/polskifrontend#179]
## Opis błędu

Chyba przestało działać pobieranie RSS, poniewarz ostatni wpis jest z 08-04-2022. To chyba błąd.

## Jak powtórzyć problem

1. Wejdź na stronę https://polskifrontend.pl/list
2. Ostatni wpis jest z 8 kwietnia
3. To chyba błąd

**Comment by jcubic** [comment]
Zgadza się wysypała się akcja: https://github.com/typeofweb/polskifrontend/actions

**Comment by jcubic** [comment]
Masz sknocone Akcje, komentarz triggeruje Build akcji: https://github.com/typeofweb/polskifrontend/actions/runs/2383050343

**Comment by mmiszy** [comment]
@allcontributors please add @jcubic for bugs

**Comment by mmiszy** [comment]
Naprawione w https://github.com/typeofweb/polskifrontend/commit/eba8b8be7d2dfc24e6bb457bf3e01dae94128b9c
