### ISSUE TITLE
[BUG] Lista artykułów nie jest odświeżana

### ISSUE THREAD

**Issue by elszczepano** [typeofweb/polskifrontend#185]
## Opis błędu

Ostatni wpis na stronie jest z 09-08-2022, lista wpisów. Lista z pewnością nie zawiera wszystkich najnowszych wpisów. Przykładowo, od tego czasu na [devszczepaniak](https://devszczepaniak.pl) pojawiło się kilka nowych publikacji.

## Jak powtórzyć problem

Przejdź na stronę https://polskifrontend.pl/list

## Oczekiwane działanie

Strona powinna ładować wszystkie posty a nie tylko wpisy sprzed kilku miesięcy

## Screenshoty

![Screenshot 2022-11-06 at 17 31 17](https://user-images.githubusercontent.com/23155008/200182745-b0059516-daa5-4d5b-a0d5-4c05c17b67e7.png)

## Twój system (uzupełnij poniżej):\*\*

- System operacyjny: MacOS 13 Ventura
- Przeglądarka 107.0.5304.87
- Wersja aplikacji: production_main_94d087f01606b24a17a98421174c5d95ecdd21b1

**Comment by mmiszy** [comment]
@allcontributors please add @elszczepano for bug

**Comment by mmiszy** [comment]
Dzięki za zgłoszenie! Bug był w konfiguracji i został poprawiony.

**Comment by mmiszy** [comment]
@allcontributors please add @elszczepano for bugs
