### ISSUE TITLE
[BUG] Lista artykułów nie jest odświeżana

### ISSUE THREAD

**Issue by elszczepano** [typeofweb/polskifrontend#195]
## Opis błędu

Ostatni wpis na stronie jest z 18 grudnia. Lista z pewnością nie zawiera wszystkich najnowszych wpisów. W przypadku widoku Grid lista nie zjest uporządkowana względem daty (czy takie zachowanie jest oczekiwane?) i ostatnie wpisy na niej pochodzą sprzed ok. pół roku. Przykładowo, od tego czasu na [devszczepaniak](https://devszczepaniak.pl) pojawiło się kilka nowych publikacji.

## Jak powtórzyć problem

Przejdź na stronę https://polskifrontend.pl/list lib https://polskifrontend.pl/grid

## Oczekiwane działanie

Strona powinna ładować wszystkie najnowsze posty, zarówno w wersji list jak i grid

## Screenshoty

![Screenshot 2023-01-18 at 21 56 17](https://user-images.githubusercontent.com/23155008/213292969-a3167ba0-b673-49a3-8503-9be94489ceb4.png)

![Screenshot 2023-01-18 at 21 57 52](https://user-images.githubusercontent.com/23155008/213293418-bf163615-e765-403b-8db0-230d4af7ca59.png)

## Twój system (uzupełnij poniżej):\*\*

- System operacyjny: macOS Version 13.1
- Przeglądarka 108.0.5359.124
- Wersja aplikacji: production_main_2618100130e7b9f60c4004301a7546605b4d2172

## Dodatkowe informacje

Najprawdopodobniej błąd zaczął występować po tej zmianie https://github.com/typeofweb/polskifrontend/commit/488ded0a32e78da24e7b099b01a03775fc41bd02

**Comment by mmiszy** [comment]
https://github.com/typeofweb/polskifrontend/commit/8af3d0a7088ec6dcb5c2cef546e2728cbe20a5d0
