### ISSUE TITLE
[Front] Responsywne kafelki artykułów/filmów

### ISSUE THREAD

**Issue by AdamSiekierski** [typeofweb/polskifrontend#27]
Aktualnie zbyt szeroki link/tekst rozpycha cały layout. Lepsze wrapowanie tekstu, odpowiedni overflow

![image](https://user-images.githubusercontent.com/24841038/102694175-af748300-421f-11eb-9ddd-4c6dbefde118.png)

**Comment by mmiszy** [comment]
overflow-wrap: break-word;
