### ISSUE TITLE
[Front] SEO

### ISSUE THREAD

**Issue by AdamSiekierski** [typeofweb/polskifrontend#44]
- Skorzystać z modułu `next/head` https://nextjs.org/docs/api-reference/next/head
- Zintegrować z komponentem Layout (np. `<Layout title="tytuł">`)
- Dodać favicon, meta tagi, etc. https://metatags.io/

**Comment by mmiszy** [comment]
Proponuję użyć modułu next-seo

**Comment by AdamSiekierski** [comment]
W czym jest lepszy od wbudowanego `next/head`?

**Comment by mmiszy** [comment]
Automatycznie potrafi generować jakieś tam rzeczy
