### ISSUE TITLE
[API] sitemap.xml

### ISSUE THREAD

**Issue by mmiszy** [typeofweb/polskifrontend#50]
Chcemy znaleźć jakiś sposób na generowanie sitemap.xml w Next.js.
Czy da się to zrobić statycznie?

**Comment by AdamSiekierski** [comment]
https://github.com/iamvishnusankar/next-sitemap To wygląda jakby miało sens

**Comment by AdamSiekierski** [comment]
Możemy utworzyć API Route, który będzie cachowany przez Vercela

https://vercel.com/docs/edge-network/caching#serverless-functions-(lambdas)
