### ISSUE TITLE
[Front] tekst w buttonach czasem łamie się na mobile

### ISSUE THREAD

**Issue by kanlukasz** [typeofweb/polskifrontend#69]
Maybe a better idea would be to reduce the font in mobile view for `OTWÓRZ` and `ORYGINAŁ`

![obraz](https://user-images.githubusercontent.com/30685349/103264203-4ffa3e00-49aa-11eb-9d6b-4ca982effdd2.png)

Tested on FF 84.0.1 (win10)

**Comment by mmiszy** [comment]
Co to za szerokość ekranu @kanlukasz ?

**Comment by kanlukasz** [comment]
![obraz](https://user-images.githubusercontent.com/30685349/103276264-5bf3f900-49c6-11eb-900f-3bbcabaefbf9.png)
