### ISSUE TITLE
[Front] Błąd 404 przez linka do feed.json

### ISSUE THREAD

**Issue by kanlukasz** [typeofweb/polskifrontend#70]
![obraz](https://user-images.githubusercontent.com/30685349/103264680-bcc20800-49ab-11eb-8e89-ce7d47945023.png)

**Comment by mmiszy** [comment]
Next myśli, że link do /feed jest podstroną i próbuje zrobić na nim preload. Ale feed nie jest stroną tylko routem api :)
Rozwiązaniem problemu będzie prawdopodobnie usunięcie <Link> i użycie tylko zwykłego <a> w tym miejscu.
