### ISSUE TITLE
[Pomysł] [Front] Przejdź do artykułu/podcastu/filmu

### ISSUE THREAD

**Issue by drillprop** [typeofweb/polskifrontend#86]
## Czy Twój pomysł jest odpowiedzią na jakiś problem?

Na tą chwilę, niezależnie czy artykuł jest filmem, podcastem czy zwyczajnym postem na blogu, treśc buttona wyświetla `przejdz do artykułu`,  jak poniżej
**
![image](https://user-images.githubusercontent.com/51168865/103384651-74affc00-4af7-11eb-9000-b60abedf9aa8.png)
**
Jest to conajmniej mylące i sprawia, że użytkownik w sumie nie wie gdzie trafi jak kliknie link. 

## Opisz swoje rozwiązanie

Ogarnąć algorytm, który podmienia buttona na odpowiednio `przejdz do artykułu` / `przejdz do filmu` / `przejdz do podcastu`

## Jakie są alternatywy?

...

## Dodatkowe informacje

…

**Comment by mmiszy** [comment]
Prawdopodobnie wystarczy proste sprawdzenie adresu url:
Jeśli pasuje do "youtube" to film
Jeśli pasuje do "anchor.fm" to podcast
Jeśli.... (tu inne przypadki)
W innym przypadku domyślny tekst
