### ISSUE TITLE
[Front] Wyśrodkowanie pozycji menu w pionie

### ISSUE THREAD

**Issue by JB1905** [typeofweb/polskifrontend#96]
Tekst i ikona w obrębie pozycji menu nie są wyśrodkowane w pionie.

Przeglądarka: Firefox 84.0.1/85.0b4
System: macOS 11.2 beta 1

Aktualnie:
<img width="1327" alt="Zrzut ekranu 2021-01-2 o 13 29 07" src="https://user-images.githubusercontent.com/28870390/103458348-56204f80-4d07-11eb-84ef-45a7e158ce50.png">

Poprawnie:
<img width="1327" alt="Zrzut ekranu 2021-01-2 o 13 28 54" src="https://user-images.githubusercontent.com/28870390/103458364-77813b80-4d07-11eb-9436-28d20123a1be.png">

**Comment by adamklepacz** [comment]
biorę
